### PR TITLE
Background image unaffected by keyboard

### LINKED ISSUE #9: Bug: Search screen container moves when keyboard opens on ios and android
### Issue Description

* Search container moves when keyboard is opened

### Steps to reproduce

1.
2.
3.

### Logs

```
<!--- Paste logs here --->
```

### PR DESCRIPTION
**Pull request by joepaji**
### Release Notes
```
Background image now unaffected by keyboard
Resolves #9 
```

### Pull request type
- [x] Bug fix
- [ ] Enhancement
- [ ] Documentation
- [ ] Other: 

### Pull request size
- [x] Tiny
- [ ] Small
- [ ] Medium
- [ ] Large

#### Describe the old behavior you are changing
- Background image moves when keyboard opens on android
- 
- 

#### Describe the new behavior from this change
- Background image no longer moves on keyboard open
- 
-

### CODE REVIEW

File: App.js [hunk 1]
```diff
@@ -102,9 +102,10 @@ const styles = StyleSheet.create({
 	},
 	background: {
 		position: "absolute",
+		zIndex: 0,
```
Comment (joepaji) [inline App.js]: This doesn't do anything, we can remove it.
